enum actionTypes {
  REQUEST_DEFAULT = "REQUEST_DEFAULT",
  REQUEST_DEFAULT_SUCCESS = "REQUEST_DEFAULT_SUCCESS",
  REQUEST_DEFAULT_ERROR = "REQUEST_DEFAULT_ERROR",
  SET_USER = "SET_USER",
}

export default actionTypes